export const EVENT_COMPONENT_SELECT = 'component:select'
export const EVENT_COMPONENT_UNSELECT = 'component:unselect'
export const EVENT_COMPONENT_SELECTION = 'component:selection'
export const EVENT_COMPONENT_ADD = 'component:add'
export const EVENT_COMPONENT_TRANSFORM = 'component:transform'
export const EVENT_COMPONENT_DELETE = 'application:delete'
export const EVENT_COMPONENT_DUPLICATE = 'application:duplicate'

export const EVENT_APPLICATION_REDO = 'application:redo'
export const EVENT_APPLICATION_UNDO = 'application:undo'
export const EVENT_APPLICATION_CLEAR = 'application:clear'
