export const EVENT_COMPONENT_SELECT = 'component:select'
export const EVENT_COMPONENT_UNSELECT = 'component:unselect'
export const EVENT_COMPONENT_SELECTION = 'component:selection'
export const EVENT_COMPONENT_ADD = 'component:add'
export const EVENT_COMPONENT_TRANSFORM = 'component:transform'
